### ISSUE TITLE
Feature: Rotate 3D pickups

### ISSUE THREAD

**Issue by aredfan** [LostArtefacts/Tomb1Main#253]
The four 3D pickups surrounding the obelisk are facing the same direction, would it be possible to rotate these so that all four pickups are facing outwards from the obelisk towards the respective drawbridges?

![1](https://user-images.githubusercontent.com/94776985/143538352-ec051727-cbdd-4823-ba51-73fa0947723d.png)

**Comment by oziphantom** [comment]
The problem is they are billboards in the original so there is no correct angle mapped for them, as they always rotate to the camera. This means we would need to detect and set their rotations, possible, however you get down to "if item number is X and level number y" type shenanigans which then break if you modify the game flow, do a randomizer etc. 

The level files have no data for this, so one can't "patch the game files". Maybe @rr-  has some ideas on said data can be added?

**Comment by ANoDE85** [comment]
If you find a solution (maybe configurable in a config file, so that the above mentioned features just use their default or have other values), there's another instance that makes the game a bit harder than it should - especially on high resolutions:
The underwater cog in The Lost Valley faces with it's side to the player, rendering it very hard to see, compared to the original sprite, which always faces the camera nicely:

![Tomb 1 Main Screenshot 2021 12 10 - 13 48 45 09](https://user-images.githubusercontent.com/22801244/145576892-7bf940e7-5adb-4a16-be86-baf2d96123c7.png)

![Tomb 1 Main Screenshot 2021 12 10 - 13 49 39 99](https://user-images.githubusercontent.com/22801244/145576922-a21600fb-66c8-4ddc-9fd4-52cf80dd0d07.png)

**Comment by ANoDE85** [comment]
I was thinking about this a bit further, and saw how the "pyramid secret fix" was implemented.
Would something similar also work for this issue - I was thinking about an entry in the gameflow json:

```
        // level 3
        {
            "title": "Lost Valley",
            "file": "data\\level3a.phd",
            "type": "normal",
            "music": 57,
            "sequence": [
                {"type": "start_game"},
                {"type": "fix_item_rotation", "room": 48, "item": "puzzle1", "rotation_x": -90},
                {"type": "loop_game"},
                {"type": "stop_game"},
                {"type": "level_stats", "level_id": 3},
                {"type": "exit_to_level", "level_id": 4},
            ],
            "strings": {
                "puzzle1": "Machine Cog"
            },
            "demo": true,
        },```

**Comment by rr-** [comment]
That's a good suggestion and I think we can go with this approach. Can someone post a complete list of pickups that need to be rotated?

**Comment by atombraiderfan** [comment]
3D pickup items in general seem to face south so this is just a trial list for the obelisk keys.  I will do a replay of TR1/UB soon and can do a complete list if someone isn't doing it already.

- Eye of Horus - rotate to west
- Seal of Anubis - rotate to east

The Ankh is already facing the correct direction which is south, The Scarab should face north but it looks the same on both sides, so is your approach to leave it alone or rotate?

**Comment by rr-** [comment]
I would say let's leave such items alone, since it's impossible to tell which way is the frontside or the backside for many other items. Even if we were to invest effort into this, it would have zero impact on the gameplay, so I don't see the point. Even custom levels, if they replace the objects with things that clearly have a distinguishable frontside and backside, they can also fix the item rotation by themselves.

**Comment by Rapora9** [comment]
> I would say let's leave such items alone, since it's impossible to tell which way is the frontside or the backside for many other items. Even if we were to invest effort into this, it would have zero impact on the gameplay, so I don't see the point. **Even custom levels, if they replace the objects with things that clearly have a distinguishable frontside and backside, they can also fix the item rotation by themselves.**

Rotating 3D pickup items in editor doesn't do anything for the items in the game itself. They always stay in the same orientation.

I was looking forward to this fix since right now I've had to design some parts of my level to take into account that you cannot rotate the pickups, and it would also be a nice quality update. For example, keys are hard to see from a certain angle, and it would also be nice to have medpacks etc. face the direction the player is coming from without having to design the rooms around that.

**Comment by ANoDE85** [comment]
I've found another pickup (minor priority) that should be rotated:
Level: "St Francis Folly" (Level4.phd)
Room: Damocles Key Room (Room 38)
Item: Damocles Key (Item 71)
(Room and Item numbers taken from trview)
![Tomb 1 Main Screenshot 2022 01 14 - 19 03 45 96](https://user-images.githubusercontent.com/22801244/149564331-4a88be2f-3337-4730-9194-1f836897f208.png)

**Comment by atombraiderfan** [comment]
I've made a list of items to rotate for Peru only, which is just five large medi packs and one machine cog (mentioned by ANoDE). [Peru pickups.txt](https://github.com/rr-/Tomb1Main/files/7874449/Peru.pickups.txt)

I also made sure to include room and item number for the pickups, based on ANoDE's last reply.  The screenshots can be found on this [imgur gallery](https://imgur.com/a/fij0JBi).

**Comment by atombraiderfan** [comment]
@rr- just a heads up that I've made a full list of pickups to rotate for TR1 only, these are mainly plot items.  I've also included screenshots for each pickup which can be viewed in the previous (edited) comment.  The list also include all items mentioned in this thread.

[TR1 pickups.txt](https://github.com/rr-/Tomb1Main/files/7894886/TR1.pickups.txt)

I'll try and get Unfinished Business list done soon.

**Comment by atombraiderfan** [comment]
Unfinished Business pickups list is done!

[TRUB pickups.txt](https://github.com/rr-/Tomb1Main/files/7920743/TRUB.pickups.txt)

[Unfinished Business gallery](https://imgur.com/a/VhZfwGV)

@rr- if the list looks good, and you need someone to test the game after implementing the changes, I'm happy to do that 👍

**Comment by Rapora9** [comment]
What about the Scion in Tomb of Qualopec? There are 3 "cinematic cameras" related to it. If you look at the Scion through the first door after avoiding the boulder, you can barely see the item with the current rotation.
![cin1](https://user-images.githubusercontent.com/97730054/153100127-7f8a4393-6dfe-490a-b8f1-c0b01fa16f2c.png)

When you come from the tunnel after the 3 doors and the dart traps, the Scion is shown well.
![cin2](https://user-images.githubusercontent.com/97730054/153100232-90011056-42f0-498a-bb0e-42fd6ea06ed7.png)

And when entering the chamber, either rotation could work.
![cin3](https://user-images.githubusercontent.com/97730054/153100332-66002642-aa60-45c2-be02-1829c0ec7928.png)

So which rotation should be prioritised? On the other hand I think the current one is good because it's more important for it to be visible when you're about to enter the room (2nd image). But on the other hand the camera would soon switch to the third angle (3rd pic) and the item could be seen well or better with 90 rotation, and also the first impression (1st image) – should player happen to take a look at the room after avoiding the boulder – would be a proper one instead of what it is now.

**Comment by atombraiderfan** [comment]
The advantage of having the sprite before is that the scion would appear presentable from both directions.  I can see the case for having the scion facing towards the first camera position, as to appear presentable for luring thieves into the boulder trap.

Personally I'm in favour of keeping to the status quo because the second camera flips and pulls away from Lara before revealing the circular form of the scion, which is cool.
