### ISSUE TITLE
OG Bug: Lara clips inside the ceiling

### ISSUE THREAD

**Issue by Rapora9** [LostArtefacts/Tomb1Main#323]
In certain places Lara can clip through the visible ceiling as if the actual ceiling was higher. For this to happen, it seems the floor below must be uneven. One such place in original TR1 is in the Caves level, near the exit door of the pit with a bear (image below).

![location](https://user-images.githubusercontent.com/97730054/149490560-9f7d27b8-9525-4f09-bb2d-7244e5653451.png)

![clipping](https://user-images.githubusercontent.com/97730054/149490861-762a05ac-ec8a-4f7a-9f39-dad26d1bb8e1.png)

I don't know of any other locations in the original TR1, but this bug is also present for example in a custom level I'm working on.

**Comment by Rapora9** [comment]
Unchecking "_Aggressive floordata packing: Scan and merge similar floordata sequences. Recommended mode for TR1-3 targets._" in Tomb Editor fixes this bug in all known instances in my custom level.

**Comment by Rapora9** [comment]
Here is another easy-to-test location where Lara goes inside the ceiling: spike room in Palace Midas.

![Näyttökuva (303)](https://user-images.githubusercontent.com/97730054/154689823-e6ba5ce8-4f15-4457-a105-9c48c3cba963.png)

If you jump so that the camera rises in that tile and goes through the ceiling too, it results in a (brief) glitchy camera angle.

![Näyttökuva (304)](https://user-images.githubusercontent.com/97730054/154690060-0339ac62-aded-4392-8a71-f4eeb980a533.png)

**Comment by lahm86** [comment]
I've found the bug and fortunately it is an easy fix. Basically `Room_GetCeiling` is not parsing the floor data properly and is at times interpreting other sector floor data as data for the current sector. #522 is caused by the same bug, so I think we should close that as a duplicate and raise the PR against this issue.

There are 309 affected locations in the original levels. I've attached an export (zipped JSON file) for interest; you can import this into trview by enabling the Randomizer Tools option in the settings window, then opening the Route window, selecting Import and changing the file type to Randomizer Locations.
[sectors.zip](https://github.com/LostArtefacts/Tomb1Main/files/11453746/sectors.zip)

Here are the specific details using the Caves example above.

`Room_GetCeiling` detects that there is a floor slant on this sector, but it fails to register that the end bit is set and so continues to read, looking for a ceiling slant.

![image](https://github.com/LostArtefacts/Tomb1Main/assets/33758420/bbb76bc2-6c07-4df4-b95c-336a5d682a79)

The next floor data index is `2861` and it just so happens that this has a ceiling slant. This is for a completely different sector however.

![image](https://github.com/LostArtefacts/Tomb1Main/assets/33758420/d6651bab-6618-4ae2-bf76-86e41f4a57a8)

So the result is that it treats that entry as valid for the current sector and so raises the ceiling height as if the slant were there. The other sector is completely arbitrary and could be anywhere on the map, the key is the next floor data index. Here is an example from Natla's Mines.

![image](https://github.com/LostArtefacts/Tomb1Main/assets/33758420/90f91a18-2902-4ed3-9c76-e832f3aab847)

![image](https://github.com/LostArtefacts/Tomb1Main/assets/33758420/9dfe20f7-f29e-4ce6-a5c3-0264c33ff87e)

I assume with aggressive floor data packing, similar floor data is collated and then floor indices are shared, so this likely greatly reduces the chances of the "next" index containing a ceiling slant.
