### ISSUE TITLE
Strange fixed-camera positions after pulling switch

### ISSUE THREAD

**Issue by aredfan** [LostArtefacts/Tomb1Main#352]
This happens when Lara pulls the switch to open the door leading into pyramid exterior.

https://user-images.githubusercontent.com/94776985/149934305-df1759e0-d766-4716-ad42-d587ff98b87d.mp4

Screenshot:

![vlcsnap-2022-01-18-12h03m34s754](https://user-images.githubusercontent.com/94776985/149934328-bcf70997-1d9c-4c74-af2d-d437630ad23c.png)

**Comment by Richard-L** [comment]
The same bug is true in the PS1 version. Video featuring some sweet switch pulling fail :)
https://user-images.githubusercontent.com/4934209/152066392-fef65da9-ab9c-4934-8582-0e97cbb5c0eb.mp4

Could it be they intentionally hid the door opening to make it harder? Would be interesting to know if the PHD contains any info.

**Comment by atombraiderfan** [comment]
The other switch in the gold maze also have a brief camera position shown for a split second before we see the door opening.

https://user-images.githubusercontent.com/94776985/152138852-e007950b-64de-45ec-b8e1-b1cf77aa6125.mp4

Screenshot:

![1](https://user-images.githubusercontent.com/94776985/152138933-d5700a7c-2d4f-43ef-b88d-3359d04648a4.png)

**Comment by Rapora9** [comment]
This (the upper one) is how it looks like if camera has 1 second timer (in custom levels made with Tomb Editor). It doesn't last 1 second but just a flashing moment. Assuming this works the same way in original TR1, my guess is that the devs just put a wrong number for the camera timer.

**Comment by aredfan** [comment]
I've come across three more switches with a brief camera angle, 1 is found in The Cistern and 2 in Tomb of Tihocan.

**Comment by aredfan** [comment]
Given that there's renewed interest in this issue, I've put together a full list of places where this bug happens, in both TR1 and TRUB.

- LEVEL7A - # 11 - Room 15 - Key
- LEVEL7B - # 163 - Room 72 - Switch
- LEVEL7B - # 223 - Room 108 - Switch
- LEVEL10A - # 87 - Room 64 - Switch
- LEVEL10A - # 90 - Room 67 - Switch
- EGYPT - # 18 - Room 12 - Pad
- END - # 304 - Room 59 - Switch
- END - # 257 - Room 40 - Switch

**Comment by lahm86** [comment]
The one frame issue when the camera shows beyond the door can be explained as follows.

The camera does a line of sight check to the door. Because it's still shut on the first frame there is a wall behind it (technically in front of it for doors that open this way). So the camera has to push through beyond the wall, but it is then obviously unable to look back at the door. On the next frame, the door begins to open, so the wall is removed and so the LOS check passes.

![image](https://github.com/LostArtefacts/Tomb1Main/assets/33758420/78b60d98-ebc5-4861-9016-fd7173894dbc)

Fixing this is going to be tricky I think. An alternative could be having a camera target to look at instead of looking at the door, but that would involve item and FD injection - not ideal. What would be ideal is finding a workaround in the camera control, but I can't think of anything at the moment.

The other issue in Natla's Mines where the camera jumps back to Lara after one frame, I'm really not sure about. The floor data here is correct; so far I've not been able to pinpoint what's causing it to cancel. I tried a camera target as well here as a test, but that behaves the same way. The timer on the camera trigger is 2 - even setting this to 0 or a very high value makes no difference.

**Comment by lahm86** [comment]
Found the bug :)

https://github.com/LostArtefacts/Tomb1Main/assets/33758420/791771ed-2725-445e-b866-d977def5059d

**Comment by aredfan** [comment]
Well done @lahm86! 🥇 

I was just checking the Saturn version (on YouTube) and it has the same bug, so in a way, this fix is a new TR1 discovery.

**Comment by lahm86** [comment]
I think the bug is present in all the games, it just needs the perfect storm for it to actually have an impact like here in Mines. I'll detail in the PR. I'm going to run a scan over all the levels to see if it's anywhere else just to be sure - although I imagine it would have been spotted elsewhere already if so. Is your list above posted today only for the second issue i.e. the one frame "through the door" problem, or are any of these the same as Mines where the camera returns to Lara?

**Comment by aredfan** [comment]
Afaik the Mines issue you've fixed is one-of-a-kind, I've never seen it occur anywhere else in TR1/UB.

Also yes, all triggers in the list (apart from LEVEL10A - # 90 - Room 67 - Switch) is related to the second issue.

**Comment by lahm86** [comment]
Great.

Would you be happy to split these issues out? I can raise a PR against this ticket for Natla's Mines. The door problem will need some further thinking and should probably have its own issue as such.

**Comment by aredfan** [comment]
More than happy to.  Thank you! 😄

**Comment by Richard-L** [comment]
What a star you are Lahm ⭐
