### ISSUE TITLE
Prevent music triggers from playing again after loading a save file

### ISSUE THREAD

**Issue by aredfan** [LostArtefacts/Tomb1Main#371]
I've noticed that music triggers can play more than once, it goes like this:

1. Lara steps on a trigger, music plays.
2. The player creates a save file afterwards.
3. The player loads the save file.
4. If Lara treads on the same trigger again, the music plays again.

This is noticable in areas where Lara have to do backtracking.

**Comment by rr-** [comment]
This error cannot be fully fixed. It also manifests in a slightly different form:

1. Lara steps on a tile triggering music track A.
2. Lara goes elsewhere and steps on a tile triggering music track B (this includes collecting a secret, for instance).
3. Lara goes back to the first tile. The game shouldn't play the music track again, but it does.

The reason for this is because the game remembers which track was played recently and even if the author of the level forgot to mark given trigger as one-shot, this logic ensures that we do not play the same music track twice in a row.

To fix this, we have two solutions: the first is to find every broken trigger in each level and mark it as a one-shot. Not very sustainable or elegant in my opinion. A second, more sensible approach would be to add to the save file information about what track was last played, letting the in-game protection against playing the same track twice in a row continue doing its job even after save and reload.

**Comment by walkawayy** [comment]
@rr- maybe marking every trigger as one shot is now possible? We already traverse them all to do calculate stats. Let me know what you think.

**Comment by rr-** [comment]
I haven't thought about this. Won't this lead to regressions?

**Comment by walkawayy** [comment]
How so? Aren't all music triggers supposed to be played only once?

**Comment by rr-** [comment]
Custom levels with Lara saying "I should revisit this area later" before a flip?

**Comment by Richard-L** [comment]
For custom levels, could people just create two triggers in the same place, to be used up in concession of game progression?
