### ISSUE TITLE
Lost Valley Black Mesh moment

### ISSUE THREAD

**Issue by Richard-L** [LostArtefacts/Tomb1Main#522]
https://user-images.githubusercontent.com/4934209/164547445-8c51f9fc-9439-4c87-ba73-a8351a717446.mp4

Noticed this on Tomb1Main-2.7-135-ge78f308_current_only_v1 while testing. Haven't seen before.
[save_tr1_00.zip](https://github.com/rr-/Tomb1Main/files/8534884/save_tr1_00.zip)

Also for some reason the camera seems choppier with this build, but maybe that's just me.

**Comment by Rapora9** [comment]
I'm pretty sure this is because of #323. See the latest comment on that issue for a similar effect.

To save you from checking the issue: Ceiling data is somehow miscalculated and Lara goes inside the ceiling a little. When the camera goes inside, the result looks like that.

To confirm, try jumping towards the ceiling there (or use the fly cheat) and see if she goes inside.

**Comment by Richard-L** [comment]
Hmm I can't seem to get her to jump into the ceiling like you show in #323. Also the fly cheat cannot reproduce the effect. It only happens when you walk up that spot with weapons equipped. Without it's fine.

**Comment by Rapora9** [comment]
You were just looking from the wrong spot. Since the camera is further back, the correct tile is this

![Näyttökuva (6)](https://user-images.githubusercontent.com/97730054/164552551-93364f60-a23a-4d78-aa1b-c0fd1071a007.png)

![Näyttökuva (7)](https://user-images.githubusercontent.com/97730054/164552579-6d065829-0018-4bf2-9f51-c73f4bb622df.png)

![Näyttökuva (5)](https://user-images.githubusercontent.com/97730054/164552597-bc2f3ea3-0ab4-4ead-b3c5-08e99532ce34.png)

**Comment by Richard-L** [comment]
Hmm, pretty sure I'd tried that, oh well.

**Comment by lahm86** [comment]
As @Rapora9 suspected, this bug is the same as #323 so will be dealt with there.
